FROM node:14

RUN apt-get update && apt-get install -y zip mc iputils-ping

WORKDIR /app

COPY ./docker-entrypoint.sh /

RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"] 

EXPOSE 8080
